# Generated by Django 3.2.7 on 2021-10-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=200, unique=True)),
                ('brand', models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.brand')),
                ('maker', models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.maker')),
            ],
        ),
    ]
